### PR TITLE
Encourage setting PHP version explicitly

### PR DESCRIPTION
**Pull request by rmccue**
See https://github.com/humanmade/altis-core/issues/590 - we should encourage users to explicitly set the PHP platform version.

### CODE REVIEW

**Comment by rmccue** [comment]
It may be worth us changing the other config change notes to use the `composer config` command too, since it's harder to do that wrong

**Review by kadamwhite — COMMENTED** [review]
I don't think this clarifies the order of operations in a way that would have prevented my issue. If I'm understanding correctly, my mistake was that I upgraded too far while trying to prepare for PHP8, and the text that has been added here doesn't give me any direction that I would have understood. What about something like,

> If you are deploying to a live environment that has not yet been upgraded to your target PHP version, the steps above may have resulted in incompatible dependencies for the current PHP version. Set the PHP version target back to the current server target and re-run update Altis with all dependencies to pin any sub dependencies at PHP 7.4-compatible versions. 

If there's a different order of operations, for example if we should only deploy Altis 12 alongside a full upgrade to PHP 8, I think that would be good to call out.

**Comment by rmccue** [comment]
The section entitled "Switch Off Composer's Platform Check" should cover this already?

**Comment by mikelittle** [comment]
Approved and merged.

**Review by mikelittle — APPROVED** [review]

**Pull request merged**
