### PR TITLE
471 docs fixes

### PR DESCRIPTION
**Pull request by jazzsequence**
Handles various typos and text fixes hightlighted in @dashaluna's review on https://github.com/humanmade/platform-dev/issues/471

Additional updates handled in https://github.com/humanmade/altis-analytics/pull/83

### CODE REVIEW

**Review by roborourke — APPROVED** [review]
Nice one Chris

**Comment by roborourke** [comment]
Do you want to handle backporting these fixes? I think they've been around since v1 but we're only supporting back to v3. You just add the backport labels and once this is merged the PRs should be created automatically.

We can go through the process together the first time though if you want before doing the actual releases.

**Comment by jazzsequence** [comment]
@roborourke is the process documented somewhere?

**Comment by roborourke** [comment]
Should be in the platform-dev docs releases guide. Can do it when you're back though.

**Pull request merged**
